# Generated by Django 4.2.16 on 2024-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataKlien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_klien', models.CharField(max_length=50)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('daerah', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
