# Generated by Django 5.1.1 on 2024-10-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataklien',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
