# Generated by Django 5.1.1 on 2024-10-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klien', '0002_dataklien_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataklien',
            name='harga_survei',
        ),
    ]
