# Generated by Django 5.1.2 on 2024-12-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDP',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('survey_name', models.CharField(max_length=255)),
                ('respondent_count', models.IntegerField()),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('paid_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doc_type', models.CharField(default='invoiceDP', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFinal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('survey_name', models.CharField(max_length=255)),
                ('respondent_count', models.IntegerField()),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('paid_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doc_type', models.CharField(default='invoiceFinal', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KwitansiDP',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('survey_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doc_type', models.CharField(default='kwitansiDP', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KwitansiFinal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('survey_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doc_type', models.CharField(default='kwitansiFinal', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
