# Generated by Django 5.1.1 on 2024-10-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDP',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('survey_name', models.CharField(max_length=255)),
                ('respondent_count', models.IntegerField()),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('paid_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceFinal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('survey_name', models.CharField(max_length=255)),
                ('respondent_count', models.IntegerField()),
                ('address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('paid_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KwitansiDP',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pembayar', models.CharField(max_length=255)),
                ('tujuan_pembayaran', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KwitansiFinal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pembayar', models.CharField(max_length=255)),
                ('tujuan_pembayaran', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
