# Generated by Django 5.1.1 on 2024-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KwitansiDP',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pembayar', models.CharField(max_length=255)),
                ('tujuan_pembayaran', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KwitansiFinal',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pembayar', models.CharField(max_length=255)),
                ('tujuan_pembayaran', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nominal_tertulis', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
