# Generated by Django 5.1.1 on 2024-11-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0002_kwitansidp_kwitansifinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedp',
            name='doc_type',
            field=models.CharField(default='invoiceDP'),
            preserve_default=False,
        ),
    ]
