# Generated by Django 5.1.1 on 2024-11-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0003_invoicedp_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefinal',
            name='doc_type',
            field=models.CharField(default='invoiceFinal'),
        ),
    ]
