# Generated by Django 5.1.1 on 2024-11-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0004_invoicefinal_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwitansidp',
            name='doc_type',
            field=models.CharField(default='kwitansiDP'),
        ),
        migrations.AddField(
            model_name='kwitansifinal',
            name='doc_type',
            field=models.CharField(default='kwitansiFinal'),
        ),
        migrations.AlterField(
            model_name='invoicedp',
            name='doc_type',
            field=models.CharField(default='invoiceDP'),
        ),
    ]
