# Generated by Django 5.1.1 on 2024-11-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0005_kwitansidp_doc_type_kwitansifinal_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedp',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicefinal',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kwitansidp',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kwitansifinal',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
