# Generated by Django 5.1.1 on 2024-11-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0006_invoicedp_isdeleted_invoicefinal_isdeleted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicedp',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='invoicefinal',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='kwitansidp',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='kwitansifinal',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
    ]
