# Generated by Django 5.1.1 on 2024-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen_pendukung', '0008_rename_pembayar_kwitansidp_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kwitansifinal',
            old_name='pembayar',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='kwitansifinal',
            name='tujuan_pembayaran',
        ),
        migrations.AddField(
            model_name='kwitansifinal',
            name='survey_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
