services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: 'no'
    environment:
      - POSTGRES_DB=siap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
