# Generated by Django 4.2.16 on 2024-10-08 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_survei', models.CharField(default='', max_length=255, unique=True)),
                ('waktu_mulai_survei', models.DateTimeField(default=datetime.datetime(2024, 10, 8, 13, 54, 26, 355065, tzinfo=datetime.timezone.utc))),
                ('waktu_berakhir_survei', models.DateTimeField(default=datetime.datetime(2024, 10, 8, 13, 54, 26, 355474, tzinfo=datetime.timezone.utc))),
                ('nama_klien', models.CharField(default='', max_length=255, unique=True)),
                ('harga_survei', models.FloatField(default=0)),
                ('ruang_lingkup_survei', models.CharField(default='', max_length=255)),
                ('wilayah_survei', models.JSONField(default=list)),
                ('jumlah_responden', models.IntegerField(default=0)),
                ('tipe_survei', models.CharField(choices=[('Lainnya', 'Lainnya'), ('Digital', 'Digital'), ('Paper-based', 'Paper-based')], default='Paper-based', max_length=255)),
            ],
        ),
    ]
