# Generated by Django 4.2.16 on 2024-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Kota', 'Kota'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
