# Generated by Django 4.1 on 2024-11-02 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import survei.models


class Migration(migrations.Migration):

    dependencies = [
        ('klien', '__first__'),
        ('survei', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survei',
            name='nama_klien',
        ),
        migrations.AddField(
            model_name='survei',
            name='klien',
            field=models.ForeignKey(default=survei.models.get_default_klien, on_delete=django.db.models.deletion.PROTECT, related_name='survei_set', to='klien.dataklien'),
        ),
        migrations.AlterField(
            model_name='survei',
            name='waktu_berakhir_survei',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='survei',
            name='waktu_mulai_survei',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='survei',
            table='survei',
        ),
    ]
