# Generated by Django 4.2.16 on 2024-11-08 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='waktu_berakhir_survei',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 10, 21, 6, 653301, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survei',
            name='waktu_mulai_survei',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 10, 21, 6, 652859, tzinfo=datetime.timezone.utc)),
        ),
    ]
