# Generated by Django 5.1.2 on 2024-12-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Kota', 'Kota'), ('Nasional', 'Nasional')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya'), ('Digital', 'Digital')], default='Paper-based', max_length=255),
        ),
    ]
