# Generated by Django 4.2.16 on 2024-11-11 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0002_alter_survei_waktu_berakhir_survei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='waktu_berakhir_survei',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 4, 39, 12, 759882, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='survei',
            name='waktu_mulai_survei',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 4, 39, 12, 759164, tzinfo=datetime.timezone.utc)),
        ),
    ]
