# Generated by Django 4.1 on 2024-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0002_remove_survei_nama_klien_survei_klien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya'), ('Digital', 'Digital')], default='Paper-based', max_length=255),
        ),
    ]
