# Generated by Django 4.1 on 2024-11-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0003_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Lainnya', 'Lainnya'), ('Digital', 'Digital'), ('Paper-based', 'Paper-based')], default='Paper-based', max_length=255),
        ),
    ]
