# Generated by Django 5.1.4 on 2024-12-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0003_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Kota', 'Kota'), ('Nasional', 'Nasional')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Digital', 'Digital'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
