# Generated by Django 5.1.2 on 2024-12-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0004_alter_survei_ruang_lingkup_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kota', 'Kota')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Paper-based', 'Paper-based'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
