# Generated by Django 5.1.3 on 2024-11-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0006_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Digital', 'Digital'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
