# Generated by Django 4.2.16 on 2024-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0013_alter_survei_tipe_survei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Digital', 'Digital'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
