# Generated by Django 5.1.2 on 2024-12-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0015_remove_survei_ruang_lingkup_survei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Kabupaten/Kota', 'Kabupaten/Kota'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Paper-based', 'Paper-based'), ('Digital', 'Digital'), ('Lainnya', 'Lainnya')], default='Paper-based', max_length=255),
        ),
    ]
