# Generated by Django 4.2.16 on 2024-12-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0019_remove_survei_ruang_lingkup_survei_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survei',
            name='ruang_lingkup',
            field=models.CharField(choices=[('Provinsi', 'Provinsi'), ('Nasional', 'Nasional'), ('Kabupaten/Kota', 'Kabupaten/Kota')], default='Nasional', max_length=255),
        ),
        migrations.AlterField(
            model_name='survei',
            name='tipe_survei',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Lainnya', 'Lainnya'), ('Paper-based', 'Paper-based')], default='Paper-based', max_length=255),
        ),
    ]
