# Generated by Django 4.2.16 on 2024-12-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0017_alter_survei_ruang_lingkup_alter_survei_tipe_survei_and_more'),
        ('survei', '0019_remove_survei_ruang_lingkup_survei_and_more'),
        ('survei', '0022_alter_survei_tipe_survei'),
    ]

    operations = [
    ]
