# Generated by Django 4.2.16 on 2024-12-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0023_merge_20241204_1202'),
        ('survei', '0023_merge_20241204_1209'),
    ]

    operations = [
    ]
