# Generated by Django 4.2.16 on 2024-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_souvennir', models.CharField(default='', max_length=255, unique=True)),
                ('jumlah_stok', models.IntegerField(default=0)),
                ('jumlah_minimum', models.IntegerField(default=0)),
            ],
        ),
    ]
