# Generated by Django 5.1.4 on 2024-12-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_souvenir', models.CharField(default='', max_length=255, unique=True)),
                ('jumlah_stok', models.IntegerField(default=0)),
                ('jumlah_minimum', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
