# Generated by Django 4.2.16 on 2024-11-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souvenir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souvenir',
            old_name='nama_souvennir',
            new_name='nama_souvenir',
        ),
    ]
