# Generated by Django 4.2.16 on 2024-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souvenir', '0002_rename_nama_souvennir_souvenir_nama_souvenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenir',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
