# Generated by Django 5.1.2 on 2024-11-01 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuatAkun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('Eksekutif', 'Eksekutif'), ('Admin Sistem', 'Admin Sistem'), ('Administrasi', 'Administrasi'), ('Logistik', 'Logistik'), ('Pengendali Mutu', 'Pengendali Mutu')], max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
