# Generated by Django 4.2.16 on 2024-10-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buatAkun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buatakun',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='buatakun',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Pengendali Mutu', 'Pengendali Mutu'), ('Manager', 'Manager')], max_length=50),
        ),
        migrations.AlterField(
            model_name='buatakun',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
