# Generated by Django 5.1.2 on 2024-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarAkun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarakun',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
