# Generated by Django 4.2.16 on 2024-10-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='tracker_survei.client')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_sent', models.BooleanField(default=False)),
                ('payment_received', models.BooleanField(default=False)),
                ('dp_invoice_sent', models.BooleanField(default=False)),
                ('contract_signed', models.BooleanField(default=False)),
                ('survey_questions_prepared', models.BooleanField(default=False)),
                ('data_analysis_started', models.BooleanField(default=False)),
                ('final_administration_completed', models.BooleanField(default=False)),
                ('report_delivered', models.BooleanField(default=False)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='tracker_survei.survey')),
            ],
        ),
    ]
