# Generated by Django 5.1.3 on 2024-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0002_trackersurvei_remove_survey_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackersurvei',
            old_name='buat_invoice',
            new_name='buat_invoice_dp',
        ),
        migrations.RenameField(
            model_name='trackersurvei',
            old_name='pembuatan_kwitansi',
            new_name='pembuatan_kwitansi_dp',
        ),
        migrations.AddField(
            model_name='trackersurvei',
            name='buat_invoice_final',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='trackersurvei',
            name='pembayaran_dp',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='trackersurvei',
            name='pembuatan_kwitansi_final',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
    ]
