# Generated by Django 4.2.16 on 2024-12-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_survei', '0003_rename_buat_invoice_trackersurvei_buat_invoice_dp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersurvei',
            name='last_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trackersurvei',
            name='pembuatan_laporan',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='trackersurvei',
            name='penyerahan_laporan',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished'), ('DELAYED', 'Delayed')], default='NOT_STARTED', max_length=20),
        ),
    ]
